DROP DATABASE Projecte_DSA;
CREATE DATABASE Projecte_DSA;
USE Projecte_DSA;

--USER INFORMATION TABLE
CREATE TABLE User(
	ID VARCHAR(36) NOT NULL DEFAULT(uuid()),
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	mail VARCHAR(255) NOT NULL,
	money DOUBLE DEFAULT 50,
	puntos INTEGER DEFAULT 0,
	PRIMARY KEY(ID)
);

--OBJECT INFORMATION TABLE
CREATE TABLE StoreObject(
	ID VARCHAR(36) NOT NULL DEFAULT(uuid()),
	name VARCHAR(255) NOT NULL,
	price DOUBLE NOT NULL,
	URL VARCHAR(255),
	PRIMARY KEY(ID)
);

--INVENTORY TABLE OF ALL USERS
CREATE TABLE Inventory(
    ID VARCHAR(36) NOT NULL DEFAULT(uuid()) PRIMARY KEY,
	UserID VARCHAR(36),
	ObjectID VARCHAR(36),
	Quantity INTEGER NOT NULL,
	FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE,
	FOREIGN KEY (ObjectID) REFERENCES StoreObject(ID) ON DELETE CASCADE
);

--EXISTING LEVELS TABLE
CREATE TABLE Nivel(
	ID VARCHAR(36) NOT NULL DEFAULT(uuid()),
	CreatorID VARCHAR(36) NOT NULL,
	name VARCHAR(255),
	PRIMARY KEY (ID),
	FOREIGN KEY (CreatorID) REFERENCES User(ID) ON DELETE CASCADE
);

--ELEMENT TYPES IN A LEVEL
CREATE TABLE Elements(
	ID VARCHAR(36) NOT NULL DEFAULT(uuid()),
	name VARCHAR(255) NOT NULL,
	effect VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

--LEVEL INFORMATION TABLE
CREATE TABLE Properties(
    ID VARCHAR(36) NOT NULL DEFAULT(uuid()) PRIMARY KEY,
	NivelID VARCHAR(36) NOT NULL,
	ElementID VARCHAR(36) NOT NULL,
	X INTEGER NOT NULL,
	Y INTEGER NOT NULL,
	FOREIGN KEY (NivelID) REFERENCES Nivel(ID) ON DELETE CASCADE,
	FOREIGN KEY (ElementID) REFERENCES Elements(ID) ON DELETE CASCADE
);

--PLAYED GAMES TABLE
CREATE TABLE Partidas(
    ID VARCHAR(36) NOT NULL DEFAULT(uuid()) PRIMARY KEY,
	UserID VARCHAR(36),
	NivelID VARCHAR(36),
	TotalTime DATETIME NOT NULL,
	PointsGiven INTEGER NOT NULL,
	FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE,
	FOREIGN KEY (NivelID) REFERENCES Nivel(ID) ON DELETE CASCADE
);